### ISSUE TITLE
Cannot connect to Regtest via Wasabi after following BTCPay server docs

### ISSUE THREAD

**Issue by AryanJ-NYC** [btcpayserver/btcpayserver-docker#287]
I'm running a BTCPay server using BTCPay server docker. If I understand it correctly, it exposes the regtest Bitcoin core through a Tor network.

I followed the tutorial [here](https://docs.btcpayserver.org/getting-started/connectwallet/wasabiwallet#connecting-wasabi-to-btcpay-server-full-node-if-youre-self-hosting-btcpay) to connect my Wasabi Wallet to the BTCPay Server full node. My Wasabi `Config.json` ends up looking like:

```
{
  "Network": "RegTest",
  "MainNetBackendUriV3": "http://oqaqivyaxctrp2gix5id4bbd7mav2xt5n4fzqsnwtrhtsmgjhg7sneqd.onion:8333/",
  "TestNetBackendUriV3": "http://oqaqivyaxctrp2gix5id4bbd7mav2xt5n4fzqsnwtrhtsmgjhg7sneqd.onion:8333/",
  "MainNetFallbackBackendUri": "http://oqaqivyaxctrp2gix5id4bbd7mav2xt5n4fzqsnwtrhtsmgjhg7sneqd.onion:8333/",
  "TestNetFallbackBackendUri": "http://oqaqivyaxctrp2gix5id4bbd7mav2xt5n4fzqsnwtrhtsmgjhg7sneqd.onion:8333/",
  "RegTestBackendUriV3": "http://oqaqivyaxctrp2gix5id4bbd7mav2xt5n4fzqsnwtrhtsmgjhg7sneqd.onion:8333/",
  "UseTor": true,
  "StartLocalBitcoinCoreOnStartup": false,
  "StopLocalBitcoinCoreOnShutdown": true,
  "LocalBitcoinCoreDataDir": "/Users/aryanjabbari/Library/Application Support/Bitcoin",
  "TorSocks5EndPoint": "127.0.0.1:9050",
  "MainNetBitcoinP2pEndPoint": "127.0.0.1:8333",
  "TestNetBitcoinP2pEndPoint": "127.0.0.1:18333",
  "RegTestBitcoinP2pEndPoint": "127.0.0.1:18444",
  "MixUntilAnonymitySet": 50,
  "PrivacyLevelSome": 2,
  "PrivacyLevelFine": 21,
  "PrivacyLevelStrong": 50,
  "DustThreshold": "0.00005"
}
```

However, in the Wasabi `Logs.txt`, I get the following error:

```
2020-03-30 11:05:01 ERROR	Global (328)	System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (61): Connection refused [::ffff:127.0.0.1]:18444
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at NBitcoin.Protocol.Connectors.SocketExtensions.<>c.<ConnectAsync>b__0_0(IAsyncResult iar)
--- End of stack trace from previous location where exception was thrown ---
   at NBitcoin.Extensions.WithCancellation[T](Task`1 task, CancellationToken cancellationToken)
   at NBitcoin.Protocol.Connectors.DefaultEndpointConnector.ConnectSocket(Socket socket, EndPoint endpoint, NodeConnectionParameters nodeConnectionParameters, CancellationToken cancellationToken)
   at NBitcoin.Protocol.Node.ConnectAsync(Network network, EndPoint endpoint, NetworkAddress peer, NodeConnectionParameters parameters)
   at WalletWasabi.Gui.Global.InitializeNoWalletAsync()
```

When I run `netstat -nap` in my bitcoind Docker container:

```
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:39388           0.0.0.0:*               LISTEN      -                   
tcp        0      0 127.0.0.11:36285        0.0.0.0:*               LISTEN      -                   
tcp        0      0 0.0.0.0:43782           0.0.0.0:*               LISTEN      -                   
tcp        0      0 172.23.0.7:43782        172.23.0.8:32854        TIME_WAIT   -                   
tcp        0      0 172.23.0.7:43782        172.23.0.5:52424        TIME_WAIT   -                   
tcp        0      0 172.23.0.7:43782        172.23.0.8:32858        TIME_WAIT   -                   
tcp        0      0 172.23.0.7:43782        172.23.0.8:32840        TIME_WAIT   -                   
tcp        0      0 172.23.0.7:43782        172.23.0.8:32856        TIME_WAIT   -                   
tcp        0      0 172.23.0.7:43782        172.23.0.5:52606        FIN_WAIT2   -                   
tcp        0      0 172.23.0.7:43782        172.23.0.8:32842        TIME_WAIT   -                   
tcp        0      0 172.23.0.7:39388        172.23.0.5:36064        ESTABLISHED -                   
tcp        0      0 172.23.0.7:43782        172.23.0.8:32844        TIME_WAIT   -                   
tcp        0      0 172.23.0.7:43782        172.23.0.8:32838        TIME_WAIT   -                   
tcp        0      0 172.23.0.7:43782        172.23.0.8:32852        TIME_WAIT   -                   
tcp6       0      0 :::39388                :::*                    LISTEN      -                   
udp        0      0 127.0.0.11:53349        0.0.0.0:*                           -   
```

In my Docker container, I try running `bitcoin-cli -regtest getnewaddress`:
```
root@04b45592faeb:/# bitcoin-cli -regtest getnewaddress
error: Could not connect to the server 127.0.0.1:18443

Make sure the bitcoind server is running and that you are connecting to the correct RPC port.
```

Then I try running `bitcoind -regtest -daemon`
```
root@f462caa968bf:/# bitcoind -regtest -daemon
Bitcoin Core starting
```

Was Bitcoin Core not running before? 🤔

FWIW, I'm quite ignorant about Bitcoin and am likely missing something along the way.

Has anyone been able to successfully connect to the `btcpayserver-docker` regtest coin via Wasabi? I have the feeling port 18444 is not being exposed.

Edit: [sister Reddit post](https://www.reddit.com/r/WasabiWallet/comments/frh7b7/having_trouble_with_regtest_running_inside_a/)

**Comment by NicolasDorier** [comment]
ugh, this is a bug in the doc.

**Comment by NicolasDorier** [comment]
@AryanJ-NYC   I fixed the doc, sorry for the confusion. Can you try again.

**Comment by AryanJ-NYC** [comment]
I tried it again. It still does not work. The documentation has made it so Wasabi no longer launches. The crash corresponds with the following error in the Wasabi logs:

```
2020-03-31 10:10:47 CRITICAL    Global (384)    System.InvalidOperationException: SocksSettingsBehavior.SocksEndpoint is not set but the connection is expecting using socks proxy
   at NBitcoin.Protocol.Connectors.DefaultEndpointConnector.ConnectSocket(Socket socket, EndPoint endpoint, NodeConnectionParameters nodeConnectionParameters, CancellationToken cancellationToken)
   at NBitcoin.Protocol.Node.ConnectAsync(Network network, EndPoint endpoint, NetworkAddress peer, NodeConnectionParameters parameters)
   at WalletWasabi.Gui.Global.InitializeNoWalletAsync()
```

**Comment by NicolasDorier** [comment]
This is strange, does socks is set on??

![image](https://user-images.githubusercontent.com/3020646/78099116-eb5e8280-741b-11ea-8c09-675093d03c84.png)

**Comment by NicolasDorier** [comment]
Because there is a possibility that tor is turned off for regtest

**Comment by AryanJ-NYC** [comment]
Yes, was as follows:
<img width="1338" alt="Screen Shot 2020-04-01 at 12 30 13 AM" src="https://user-images.githubusercontent.com/8263430/78099494-0c898980-73b0-11ea-8b8b-0573db2b1760.png">

Upon attempting to restart, I got the same Wasabi error in `/.walletwasabi/client/Logs.txt`:
```
2020-04-01 00:30:27 CRITICAL	Global (384)	System.InvalidOperationException: SocksSettingsBehavior.SocksEndpoint is not set but the connection is expecting using socks proxy
   at NBitcoin.Protocol.Connectors.DefaultEndpointConnector.ConnectSocket(Socket socket, EndPoint endpoint, NodeConnectionParameters nodeConnectionParameters, CancellationToken cancellationToken)
   at NBitcoin.Protocol.Node.ConnectAsync(Network network, EndPoint endpoint, NetworkAddress peer, NodeConnectionParameters parameters)
   at WalletWasabi.Gui.Global.InitializeNoWalletAsync()
```

**Comment by AryanJ-NYC** [comment]
I used the `oqaqivyaxctrp2gix5id4bbd7mav2xt5n4fzqsnwtrhtsmgjhg7sneqd.onion:8333` as the Bitcoin P2P endpoint for `TestNet` and that worked just fine. It's only `RegTest` that is the problem.

**Comment by NicolasDorier** [comment]
yes, so that mean wasabi is not using SOCKS for regtest (probably because it make testing easier).
You can maybe activate it in the settings, if not then you should ask them to make that possible.

**Comment by AryanJ-NYC** [comment]
OK, great. I'll open an issue on their board. I appreciate the help!

**Comment by AryanJ-NYC** [comment]
I've messed around with the Wasabi code and was able to build a GUI that successfully connects to the Tor network running in the Docker container.

However, I still get the following:

```
2020-04-01 11:06:31 ERROR	WasabiSynchronizer (306)	System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (61): Connection refused [::ffff:127.0.0.1]:37127
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(Object result, MultipleAddressConnectAsyncResult context)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(Object result, MultipleAddressConnectAsyncResult context)
   at System.Net.Sockets.Socket.MultipleAddressConnectCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.TcpClient.<>c.<ConnectAsync>b__28_1(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at WalletWasabi.TorSocks5.TorSocks5Client.ConnectToDestinationAsync(String host, Int32 port, Boolean isRecursiveCall) in /Users/aryanjabbari/Documents/practice/WalletWasabi/WalletWasabi/TorSocks5/TorSocks5Client.cs:line 217
   at WalletWasabi.TorSocks5.TorHttpClient.SendAsync(HttpRequestMessage request, CancellationToken cancel) in /Users/aryanjabbari/Documents/practice/WalletWasabi/WalletWasabi/TorSocks5/TorHttpClient.cs:line 195
   at WalletWasabi.TorSocks5.TorHttpClient.SendAsync(HttpMethod method, String relativeUri, HttpContent content, CancellationToken cancel) in /Users/aryanjabbari/Documents/practice/WalletWasabi/WalletWasabi/TorSocks5/TorHttpClient.cs:line 112
   at TorHttpClientExtensions.SendAndRetryAsync(ITorHttpClient client, HttpMethod method, HttpStatusCode expectedCode, String relativeUri, Int32 retry, HttpContent content, CancellationToken cancel) in /Users/aryanjabbari/Documents/practice/WalletWasabi/WalletWasabi/Extensions/TorHttpClientExtensions.cs:line 20
   at WalletWasabi.WebClients.Wasabi.WasabiClient.GetSynchronizeAsync(uint256 bestKnownBlockHash, Int32 count, Nullable`1 estimateMode, CancellationToken cancel) in /Users/aryanjabbari/Documents/practice/WalletWasabi/WalletWasabi/WebClients/Wasabi/WasabiClient.cs:line 55
   at System.Threading.Tasks.TaskExtensions.WithAwaitCancellationAsync[T](Task`1 me, CancellationToken cancel, Int32 waitForGracefulTerminationMilliseconds) in /Users/aryanjabbari/Documents/practice/WalletWasabi/WalletWasabi/Extensions/TaskExtensions.cs:line 33
   at WalletWasabi.Services.WasabiSynchronizer.<>c__DisplayClass60_0.<<Start>b__0>d.MoveNext() in /Users/aryanjabbari/Documents/practice/WalletWasabi/WalletWasabi/Services/WasabiSynchronizer.cs:line 181
```

What should the `RegTestBackendUriV3` setting be set to here?  I've tried `http://127.0.0.1:8333`, `http://127.0.0.1:18333` and `http://127.0.0.1:18444`, all with no luck.

**Comment by NicolasDorier** [comment]
Closing this, as this depends on https://github.com/zkSNACKs/WalletWasabi/issues/3427
