### ISSUE TITLE
Bump Upstream Version of elements core docker image

### ISSUE THREAD

**Issue by petzsch** [btcpayserver/btcpayserver-docker#296]
It would be great to have the most recent elements core version (0.18.1.6) in the docker deployment.
Main change I'm intrested in according to https://github.com/ElementsProject/elements/releases

- Reduce mintxfee to 0.1 sat/vbyte and fallback fee to 2 sat/vb

Thanks.

**Comment by Kukks** [comment]
Just did a bump, CI publishing docker images soon. Can you test it for us by changing the docker image to `btcpayserver/elements:0.18.1.6` and seeing if it works ok?

**Comment by Kukks** [comment]
Did a booboo, republishing the images

**Comment by petzsch** [comment]
Kind of busy here at the moment. I'll test it tomorrow and give you feedback then.

**Comment by petzsch** [comment]
test looks good so far:

tx fees are now at 0,1 sat / vB

Only problem is opening the wallet page of the LBTC wallet (error 500), opening the USDt wallet page works. Here is the log output:

https://pastebin.com/1QAW7BA5

**Comment by petzsch** [comment]
Did some more testing with this version on a fresh BTCPayServer install.

It appears the error 500 starts appearing as soon as you do the first liquid btc withdrawel from elements-cli.sh.

Don't know if it helps to narrow the error down. Let me know, if you need more logs or anything.

**Comment by NicolasDorier** [comment]
@petzsch can you give us the logs? Ping @Kukks seems like a bit in liquid integration.

**Comment by petzsch** [comment]
```
2020-05-02 09:35:42.142 +00:00 [INF] User logged in.
2020-05-02 09:35:55.130 +00:00 [ERR] Connection id "0HLVDL1EPJIP8", Request id "0HLVDL1EPJIP8:00000001": An unhandled exception was thrown by the application.
System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Number.ParseDecimal(ReadOnlySpan`1 value, NumberStyles styles, NumberFormatInfo info)
   at BTCPayServer.MoneyExtensions.Convert(Int64 sats, Int32 divisibility) in /source/BTCPayServer/Extensions/MoneyExtensions.cs:line 34
   at BTCPayServer.MoneyExtensions.<>c__DisplayClass0_0.<GetValue>b__0(IMoney money) in /source/BTCPayServer/Extensions/MoneyExtensions.cs:line 18
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.Sum(IEnumerable`1 source)
   at BTCPayServer.Controllers.WalletsController.WalletTransactions(WalletId walletId, String labelFilter) in /source/BTCPayServer/Controllers/WalletsController.cs:line 282
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at BTCPayServer.Hosting.BTCPayMiddleware.Invoke(HttpContext httpContext) in /source/BTCPayServer/Hosting/BTCpayMiddleware.cs:line 78
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at BTCPayServer.Hosting.HeadersOverrideMiddleware.Invoke(HttpContext httpContext) in /source/BTCPayServer/Hosting/HeadersOverrideMiddleware.cs:line 32
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)

```

That appears in the logs when I try to open the wallet page of my LBTC hot wallet. (setup the way the documentation suggested to)

Also note, I've upgraded to: btcpayserver/elements:0.18.1.7 in the meantime to see if the fee estimation works better now. (spoiler: it doesn't really... sits at 99 sat/Byte now)

**Comment by Kukks** [comment]
If I'm not mistaken, this bug should be fixed in the next version. Re-open if it isn't

**Comment by petzsch** [comment]
Seems to be an issue still (getting error 500) and this in the logs whenever I try to browse the LBTC wallet that has spends in it:

```
2020-05-19 11:55:16.705 +00:00 [ERR] Connection id "0HLVR7IR9511C", Request id "0HLVR7IR9511C:00000001": An unhandled exception was thrown by the application.
System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Number.ParseDecimal(ReadOnlySpan`1 value, NumberStyles styles, NumberFormatInfo info)
   at System.Decimal.Parse(String s, IFormatProvider provider)
   at BTCPayServer.MoneyExtensions.Convert(Int64 sats, Int32 divisibility) in /source/BTCPayServer/Extensions/MoneyExtensions.cs:line 37
   at BTCPayServer.MoneyExtensions.<>c__DisplayClass0_0.<GetValue>b__0(IMoney money) in /source/BTCPayServer/Extensions/MoneyExtensions.cs:line 18
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.Sum(IEnumerable`1 source)
   at BTCPayServer.Controllers.WalletsController.WalletTransactions(WalletId walletId, String labelFilter) in /source/BTCPayServer/Controllers/WalletsController.cs:line 282
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at BTCPayServer.Hosting.BTCPayMiddleware.Invoke(HttpContext httpContext) in /source/BTCPayServer/Hosting/BTCpayMiddleware.cs:line 78
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at BTCPayServer.Hosting.HeadersOverrideMiddleware.Invoke(HttpContext httpContext) in /source/BTCPayServer/Hosting/HeadersOverrideMiddleware.cs:line 32
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)

```
